name: Scheduled Message Collection

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  collect-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request to Vercel endpoint
        run: |
          curl -X POST https://discord-extract-node.vercel.app/api/cron
